<?php

/**
 * BasePhoto
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $gallery_id
 * @property string $description
 * @property string $path
 * @property Gallery $Gallery
 * 
 * @method integer getGalleryId()   Returns the current record's "gallery_id" value
 * @method string  getDescription() Returns the current record's "description" value
 * @method string  getPath()        Returns the current record's "path" value
 * @method Gallery getGallery()     Returns the current record's "Gallery" value
 * @method Photo   setGalleryId()   Sets the current record's "gallery_id" value
 * @method Photo   setDescription() Sets the current record's "description" value
 * @method Photo   setPath()        Sets the current record's "path" value
 * @method Photo   setGallery()     Sets the current record's "Gallery" value
 * 
 * @package    swbrasil
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePhoto extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('photo');
        $this->hasColumn('gallery_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('description', 'string', 100, array(
             'type' => 'string',
             'notnull' => false,
             'length' => '100',
             ));
        $this->hasColumn('path', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '100',
             ));

        $this->option('type', 'MyISAM');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Gallery', array(
             'local' => 'gallery_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}