<?php

/**
 * BaseGallery
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $title
 * @property string $slug
 * @property string $description
 * @property Doctrine_Collection $Photos
 * 
 * @method string              getTitle()       Returns the current record's "title" value
 * @method string              getSlug()        Returns the current record's "slug" value
 * @method string              getDescription() Returns the current record's "description" value
 * @method Doctrine_Collection getPhotos()      Returns the current record's "Photos" collection
 * @method Gallery             setTitle()       Sets the current record's "title" value
 * @method Gallery             setSlug()        Sets the current record's "slug" value
 * @method Gallery             setDescription() Sets the current record's "description" value
 * @method Gallery             setPhotos()      Sets the current record's "Photos" collection
 * 
 * @package    swbrasil
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseGallery extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('gallery');
        $this->hasColumn('title', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '100',
             ));
        $this->hasColumn('slug', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => '100',
             ));
        $this->hasColumn('description', 'string', null, array(
             'type' => 'string',
             'notnull' => false,
             ));

        $this->option('type', 'MyISAM');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Photo as Photos', array(
             'local' => 'id',
             'foreign' => 'gallery_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}