<?php

/**
 * BaseGuestbook
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $email
 * @property string $city
 * @property string $state
 * @property string $country
 * @property string $comment
 * @property boolean $approved
 * 
 * @method string    getName()     Returns the current record's "name" value
 * @method string    getEmail()    Returns the current record's "email" value
 * @method string    getCity()     Returns the current record's "city" value
 * @method string    getState()    Returns the current record's "state" value
 * @method string    getCountry()  Returns the current record's "country" value
 * @method string    getComment()  Returns the current record's "comment" value
 * @method boolean   getApproved() Returns the current record's "approved" value
 * @method Guestbook setName()     Sets the current record's "name" value
 * @method Guestbook setEmail()    Sets the current record's "email" value
 * @method Guestbook setCity()     Sets the current record's "city" value
 * @method Guestbook setState()    Sets the current record's "state" value
 * @method Guestbook setCountry()  Sets the current record's "country" value
 * @method Guestbook setComment()  Sets the current record's "comment" value
 * @method Guestbook setApproved() Sets the current record's "approved" value
 * 
 * @package    swbrasil
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseGuestbook extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('guestbook');
        $this->hasColumn('name', 'string', 150, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '150',
             ));
        $this->hasColumn('email', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '100',
             ));
        $this->hasColumn('city', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '100',
             ));
        $this->hasColumn('state', 'string', 2, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '2',
             ));
        $this->hasColumn('country', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '50',
             ));
        $this->hasColumn('comment', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             ));
        $this->hasColumn('approved', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));

        $this->option('type', 'MyISAM');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}