# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/11-App

# default values
all:
  tiny_mce:
    my_settings:
      mode : textareas
      theme : advanced
      plugins: 'ibrowser'
      extended_valid_elements : 'iframe[src|width|height|name|align]'
      theme_advanced_buttons1 : 'save,newdocument,|,bold,italic,underline,strikethrough,|,justifyleft,justifycenter,justifyright,justifyfull,formatselect,fontselect,fontsizeselect,|,code,|,ibrowser,|,html'
      theme_advanced_buttons2 : 'cut,copy,paste,pastetext,pasteword,|,search,replace,|,bullist,numlist,|,outdent,indent,blockquote,|,undo,redo,|,link,unlink,anchor,image,cleanup,forecolor,backcolor'
      theme_advanced_buttons3 : ''
      theme_advanced_toolbar_location : 'top'
      theme_advanced_toolbar_align : 'left'
      theme_advanced_resizing : true
  sfImageTransformPlugin:
    default_adapter: GD # GD or ImageMagick
    default_image:
      mime_type: image/png
      filename: Untitled.png
      width: 100
      height: 100
      color: '#FFFFFF'
    font_dir: /usr/share/fonts/truetype/msttcorefonts
    mime_type:
      auto_detect: false
      library: Fileinfo #  gd_mime_type (GD), Fileinfo (PECL), MIME_Type (PEAR)
