# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
homepage:
  url:   /
  param: { module: capa, action: index }

error:
  url: /error/404
  param: { module: error, action: 404 }

gallery_view:
  url: /album/:slug
  param: { module: gallery, action: view }

gallery_list:
  url: /albuns/*
  param: { module: gallery, action: list }

download_file:
  url: /download/:file/:type
  param: { module: download, action: download }
  
guestbook_list:
  url: /livrodevisitas/*
  param: { module: guestbook, action: list }
  
contact:
  url: /contato/*
  param: { module: contact, action: index }
  
links:
  url: /links
  param: { module: link, action: list }

news_view:
  url: /noticia/:slug
  param: { module: news, action: view }
  
news_list_blank:
  url: /noticias
  param: { module: news, action: list }
  
news_list:
  url: /noticias/pg/:page
  param: { module: news, action: list }  
  
professional_list:
  url: /profissionais/*
  param: { module: professional, action: list }
 
friend_list:
  url: /amigos/*
  param: { module: friend, action: list }  


page_view:
  url: /:slug_category/:slug_page
  param: { module: page, action: view }

# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
