# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    title:        Website Oficial Da Associação Brasileira da Síndrome de Williams
    description:  Melhorar a qualidade de vida das pessoas com SW, promovendo campanhas de esclarecimento em geral, quanto às suas reais possibilidades de incluir-se na rede regular de ensino, em cursos profissionalizantes, no mercado de trabalho e em todas as atividades da sociedade a qual pertence
    keywords:     sindrome, williams, beuren, brasil, trespach
    language:     pt-BR
    robots:       index, follow

  stylesheets:    [screen.css, main.css, print.css { media: print }, ie.css { condition: IE }]

  javascripts:    []

  has_layout:     true
  layout:         layout
