<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2010/04/01 19:08:19

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=swbrasil',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
