all:
  stylesheets:    [jquery.lightbox-0.5.css]

  javascripts:    [jquery.lightbox-0.5.min.js, lightbox.js]

  has_layout:     true
  layout:         layout

  jquery_web_dir:         false
  jquery_core:            jquery-1.4.2.min.js
