generator:
  class: sfDoctrineGenerator
  param:
    model_class:           article
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:
    route_prefix:          article
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        category_id:
          label: Categoria
        category:
          label: Categoria
        title:
          label: Titulo
        content:
          label: Conteúdo
      list:
        display: [title, category]
        title: Lista de Páginas
      filter:
        class: false
      form: ~
      edit:
        title: Alterar Página "%%title%%"
      new:
        title: Criar Página
